project 'BeautyHouse.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10'
inhibit_all_warnings!

target 'BeautyHouse' do
  
    use_frameworks!
	pod 'AVOSCloud'
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'JSONModel'
end
