project 'BeautyHouse.xcodeproj'

# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10'
inhibit_all_warnings!

target 'BeautyHouse' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
	pod 'AVOSCloud'
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'JSONModel'
end
